"""
2026 MLB Totals Backtest — Kalshi Closing Prices

Uses the last trade before first pitch (closing line) rather than the 10 AM PT
morning snapshot, giving a truer picture of the live-bet opportunity.

Prerequisites:
    python collect_kalshi_historical.py --mode closing --season 2026

Usage:
    python backtest_2026.py
    python backtest_2026.py --season 2026
    python backtest_2026.py --bankroll 10000

Output:
    data/backtest_2026_results.tsv   — one row per game
    data/backtest_2026_summary.json  — aggregate statistics
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

import pandas as pd

try:
    import yaml
    _YAML_AVAILABLE = True
except ImportError:
    _YAML_AVAILABLE = False

# Reuse existing prediction/model infrastructure — no logic duplicated here.
from model_runtime import load_model_bundle
from prediction_betting import (
    add_kalshi_metrics,
    get_kalshi_betting_thresholds,
    kalshi_filter_reason,
)

# load_features_2026 and predict_all live in simulate_2026_season; import them.
from simulate_2026_season import (
    find_consensus,
    load_features_2026,
    predict_all,
)

# ─────────────────────────────────────────────────────────────────────────────
PROJECT_DIR = Path(__file__).resolve().parent
DATA_DIR = PROJECT_DIR / "data"

CLOSING_LINES_PATH = DATA_DIR / "kalshi_closing_lines_2026.tsv"
RESULTS_PATH = DATA_DIR / "backtest_2026_results.tsv"
SUMMARY_PATH = DATA_DIR / "backtest_2026_summary.json"


# ─────────────────────────────────────────────────────────────────────────────
# Config helpers
# ─────────────────────────────────────────────────────────────────────────────

def load_config() -> dict:
    if _YAML_AVAILABLE:
        config_path = PROJECT_DIR / "model_config.yaml"
        if config_path.exists():
            with config_path.open(encoding="utf-8") as f:
                return yaml.safe_load(f) or {}
    return {}


# ─────────────────────────────────────────────────────────────────────────────
# Closing-line loader
# ─────────────────────────────────────────────────────────────────────────────

def load_kalshi_closing() -> dict:
    """
    Returns {(date_str, away_team, home_team): {strike: yes_price}}
    for strikes that had a valid closing-price trade.
    """
    if not CLOSING_LINES_PATH.exists():
        print(
            "\nERROR: Closing lines file not found.\n"
            "Run: python collect_kalshi_historical.py --mode closing --season 2026\n"
        )
        raise SystemExit(1)

    df = pd.read_csv(CLOSING_LINES_PATH, sep="\t")

    if "has_closing_price" not in df.columns:
        print(
            "\nERROR: Column 'has_closing_price' missing from closing lines file.\n"
            "The file may have been generated by an older version of the collector.\n"
            "Run: python collect_kalshi_historical.py --mode closing --season 2026\n"
        )
        raise SystemExit(1)

    if "api_failed" not in df.columns:
        df["api_failed"] = False

    df = df[df["has_closing_price"] == True].dropna(subset=["yes_price"])

    result: dict = {}
    for row in df.itertuples(index=False):
        key = (str(row.date), row.away_team, row.home_team)
        result.setdefault(key, {})[float(row.strike)] = float(row.yes_price)
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Core backtest loop
# ─────────────────────────────────────────────────────────────────────────────

def _no_bet_row(
    date_str: str,
    away: str,
    home: str,
    predicted: float,
    actual: float,
    reason: str,
    **extras,
) -> dict:
    return {
        "date": date_str,
        "away_team": away,
        "home_team": home,
        "predicted_total": round(float(predicted), 2),
        "kalshi_line": extras.get("kalshi_line"),
        "kalshi_yes_price": extras.get("kalshi_yes_price"),
        "kalshi_side": None,
        "kalshi_edge_pct": extras.get("kalshi_edge_pct"),
        "kalshi_fair_price_pct": extras.get("kalshi_fair_price_pct"),
        "kalshi_side_model_prob": extras.get("kalshi_side_model_prob"),
        "kalshi_side_market_prob": extras.get("kalshi_side_market_prob"),
        "bet_amount": 0.0,
        "bet_pct_bankroll": 0.0,
        "actual_total": actual,
        "result": "no_bet",
        "pnl_dollars": 0.0,
        "roi_pct": 0.0,
        "settled": False,
        "skip_reason": reason,
    }


def run_backtest(
    preds_df: pd.DataFrame,
    closing: dict,
    bankroll_cfg: dict,
    display_cfg: dict,
    min_kalshi_edge_pct: float = 0.0,
    min_kalshi_confidence_pct: float = 0.0,
) -> pd.DataFrame:
    rows = []
    running_bankroll = float(bankroll_cfg.get("total", 10000))
    max_line_diff = float(display_cfg.get("kalshi_max_line_diff", 2.5))

    for _, game in preds_df.sort_values(["date", "game_id"]).iterrows():
        date_str = str(pd.Timestamp(game["date"]).date())
        away = game["away_team"]
        home = game["home_team"]
        actual = float(game["total_runs"])
        key = (date_str, away, home)

        strike_prices = closing.get(key)
        if not strike_prices:
            rows.append(
                _no_bet_row(
                    date_str, away, home,
                    predicted=game["predicted_total"],
                    actual=actual,
                    reason="no_closing_line",
                )
            )
            continue

        consensus = find_consensus(strike_prices)
        if consensus is None:
            rows.append(
                _no_bet_row(
                    date_str, away, home,
                    predicted=game["predicted_total"],
                    actual=actual,
                    reason="no_consensus",
                )
            )
            continue

        kalshi_line, yes_price = consensus

        # Build the same pred dict that the live bot / simulator uses so we can
        # call add_kalshi_metrics() and kalshi_filter_reason() unchanged.
        pred = {
            "game_id": game.get("game_id"),
            "away_team": away,
            "home_team": home,
            "predicted_total": float(game["predicted_total"]),
            "prediction_std": float(game["prediction_std"]),
            "high_tail_prob_9p5": (
                float(game["high_tail_prob_9p5"])
                if pd.notna(game.get("high_tail_prob_9p5"))
                else None
            ),
            "low_tail_prob_7p5": (
                float(game["low_tail_prob_7p5"])
                if pd.notna(game.get("low_tail_prob_7p5"))
                else None
            ),
            "kalshi_line": float(kalshi_line),
            "kalshi_over_pct": float(yes_price) * 100.0,
            "kalshi_yes_ask": float(yes_price),
            "_bankroll_cfg": dict(bankroll_cfg, total=running_bankroll),
            "_high_tail_cfg": None,
            "_low_tail_cfg": None,
        }

        add_kalshi_metrics(pred, residual_std=float(game["prediction_std"]))

        reason = kalshi_filter_reason(
            pred,
            max_line_diff=max_line_diff,
            min_edge_pct=min_kalshi_edge_pct,
            min_confidence_pct=min_kalshi_confidence_pct,
        )

        common_extras = dict(
            kalshi_line=pred["kalshi_line"],
            kalshi_yes_price=yes_price,
            kalshi_side_market_prob=pred.get("kalshi_side_market_prob"),
            kalshi_fair_price_pct=pred.get("kalshi_fair_price_pct"),
            kalshi_edge_pct=pred.get("kalshi_edge_pct"),
            kalshi_side_model_prob=pred.get("kalshi_side_model_prob"),
        )

        if reason is not None:
            rows.append(
                _no_bet_row(
                    date_str, away, home,
                    predicted=game["predicted_total"],
                    actual=actual,
                    reason=reason,
                    **common_extras,
                )
            )
            continue

        kelly = pred.get("kalshi_kelly") or {}
        bet_amount = float(kelly.get("recommended_bet", 0.0) or 0.0)
        bet_pct_bankroll = (
            (bet_amount / running_bankroll * 100.0) if running_bankroll > 0 else 0.0
        )
        side = pred.get("kalshi_side")
        market_price = float(pred.get("kalshi_side_market_prob", 0.0) or 0.0) / 100.0

        won = None
        pnl = 0.0
        roi_pct = 0.0
        settled = False
        result = "no_bet" if bet_amount <= 0 else "pending"

        if bet_amount > 0:
            actual_over = actual > float(pred["kalshi_line"])
            won = (side == "OVER" and actual_over) or (side == "UNDER" and not actual_over)
            pnl = (
                bet_amount * ((1.0 - market_price) / market_price)
                if won
                else -bet_amount
            )
            running_bankroll += pnl
            roi_pct = (pnl / bet_amount * 100.0) if bet_amount > 0 else 0.0
            settled = True
            result = "win" if won else "loss"

        rows.append({
            "date": date_str,
            "away_team": away,
            "home_team": home,
            "predicted_total": round(float(game["predicted_total"]), 2),
            "kalshi_line": float(pred["kalshi_line"]),
            "kalshi_yes_price": float(yes_price),
            "kalshi_side": side,
            "kalshi_edge_pct": float(pred.get("kalshi_edge_pct", 0.0) or 0.0),
            "kalshi_fair_price_pct": float(pred.get("kalshi_fair_price_pct", 0.0) or 0.0),
            "kalshi_side_model_prob": float(pred.get("kalshi_side_model_prob", 0.0) or 0.0),
            "kalshi_side_market_prob": float(pred.get("kalshi_side_market_prob", 0.0) or 0.0),
            "bet_amount": round(bet_amount, 2),
            "bet_pct_bankroll": round(bet_pct_bankroll, 3),
            "actual_total": actual,
            "result": result,
            "pnl_dollars": round(pnl, 2),
            "roi_pct": round(roi_pct, 2),
            "settled": settled,
            "skip_reason": None if bet_amount > 0 else "kelly_below_min_bet",
        })

    return pd.DataFrame(rows)


# ─────────────────────────────────────────────────────────────────────────────
# Summary builder
# ─────────────────────────────────────────────────────────────────────────────

def build_summary(results: pd.DataFrame, starting_bankroll: float) -> dict:
    total_games = int(len(results))
    games_with_closing = int(results["kalshi_line"].notna().sum())

    bets = results[results["bet_amount"] > 0].copy()
    settled = bets[bets["settled"] == True].copy()

    wins = int((settled["result"] == "win").sum())
    losses = int((settled["result"] == "loss").sum())
    total_bets = wins + losses
    total_wagered = float(settled["bet_amount"].sum())
    total_pnl = float(settled["pnl_dollars"].sum())
    roi_pct = (total_pnl / total_wagered * 100.0) if total_wagered > 0 else 0.0
    win_rate = (wins / total_bets * 100.0) if total_bets > 0 else 0.0
    avg_edge = float(bets["kalshi_edge_pct"].dropna().mean()) if not bets.empty else 0.0

    # Over / Under breakdown
    over_bets_df = settled[settled["kalshi_side"] == "OVER"]
    under_bets_df = settled[settled["kalshi_side"] == "UNDER"]
    over_wins = int((over_bets_df["result"] == "win").sum())
    under_wins = int((under_bets_df["result"] == "win").sum())
    over_total = len(over_bets_df)
    under_total = len(under_bets_df)

    # By-month breakdown
    by_month: dict = {}
    if not settled.empty:
        settled_copy = settled.copy()
        settled_copy["month"] = pd.to_datetime(settled_copy["date"]).dt.strftime("%Y-%m")
        for month, grp in settled_copy.groupby("month"):
            m_wins = int((grp["result"] == "win").sum())
            m_losses = int((grp["result"] == "loss").sum())
            m_total = m_wins + m_losses
            m_wagered = float(grp["bet_amount"].sum())
            m_pnl = float(grp["pnl_dollars"].sum())
            by_month[month] = {
                "bets": m_total,
                "wins": m_wins,
                "losses": m_losses,
                "win_rate": round(m_wins / m_total * 100.0, 1) if m_total > 0 else 0.0,
                "total_wagered": round(m_wagered, 2),
                "total_pnl": round(m_pnl, 2),
                "roi_pct": round(m_pnl / m_wagered * 100.0, 2) if m_wagered > 0 else 0.0,
            }

    return {
        "total_games": total_games,
        "games_with_closing_lines": games_with_closing,
        "bets_placed": total_bets,
        "wins": wins,
        "losses": losses,
        "win_rate": round(win_rate, 1),
        "roi_pct": round(roi_pct, 2),
        "total_pnl": round(total_pnl, 2),
        "total_wagered": round(total_wagered, 2),
        "avg_edge_pct": round(avg_edge, 2),
        "over_bets": over_total,
        "under_bets": under_total,
        "over_win_rate": round(over_wins / over_total * 100.0, 1) if over_total > 0 else 0.0,
        "under_win_rate": round(under_wins / under_total * 100.0, 1) if under_total > 0 else 0.0,
        "by_month": by_month,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="2026 MLB totals backtest using Kalshi closing prices."
    )
    parser.add_argument("--season", type=int, default=2026)
    parser.add_argument("--bankroll", type=float, default=None)
    parser.add_argument("--kelly-fraction", type=float, default=None)
    parser.add_argument("--max-bet-pct", type=float, default=None)
    parser.add_argument("--min-bet", type=float, default=None)
    parser.add_argument("--round-to", type=float, default=None)
    parser.add_argument("--min-kalshi-edge-pct", type=float, default=None)
    parser.add_argument("--min-kalshi-confidence-pct", type=float, default=None)
    args = parser.parse_args()

    cfg = load_config()
    bankroll_cfg = dict(cfg.get("bankroll", {}) or {})
    bet_cfg = cfg.get("betting", {}) or {}
    kalshi_thresholds = get_kalshi_betting_thresholds(bet_cfg)
    display_cfg = cfg.get("display", {}) or {}

    # CLI overrides
    if args.bankroll is not None:
        bankroll_cfg["total"] = float(args.bankroll)
    if args.kelly_fraction is not None:
        bankroll_cfg["kelly_fraction"] = float(args.kelly_fraction)
    if args.max_bet_pct is not None:
        bankroll_cfg["max_bet_pct"] = float(args.max_bet_pct)
    if args.min_bet is not None:
        bankroll_cfg["min_bet"] = float(args.min_bet)
    if args.round_to is not None:
        bankroll_cfg["round_to"] = float(args.round_to)

    min_kalshi_edge_pct = (
        float(args.min_kalshi_edge_pct)
        if args.min_kalshi_edge_pct is not None
        else float(kalshi_thresholds["min_kalshi_edge_pct"])
    )
    min_kalshi_confidence_pct = (
        float(args.min_kalshi_confidence_pct)
        if args.min_kalshi_confidence_pct is not None
        else float(kalshi_thresholds["min_kalshi_confidence_pct"])
    )

    starting_bankroll = float(bankroll_cfg.get("total", 10000))

    print(f"=== 2026 Backtest — Kalshi Closing Prices ===")

    print("Loading closing Kalshi lines...")
    closing = load_kalshi_closing()
    print(f"  {sum(len(v) for v in closing.values())} strike rows across {len(closing)} games")

    print("Loading model bundle...")
    bundle = load_model_bundle()

    print(f"Loading {args.season} feature rows...")
    feat_df = load_features_2026(args.season)
    print(f"  {len(feat_df)} rows loaded")

    print("Running predictions...")
    preds_df = predict_all(feat_df, bundle)
    print(
        f"  {len(preds_df)} games predicted "
        f"(mean total {preds_df['predicted_total'].mean():.2f})"
    )

    matched = sum(
        1
        for _, row in preds_df.iterrows()
        if (
            str(pd.Timestamp(row["date"]).date()),
            row["away_team"],
            row["home_team"],
        ) in closing
    )
    print(f"  {matched}/{len(preds_df)} games matched to closing lines")

    print("Running backtest...")
    results = run_backtest(
        preds_df,
        closing,
        bankroll_cfg,
        display_cfg,
        min_kalshi_edge_pct=min_kalshi_edge_pct,
        min_kalshi_confidence_pct=min_kalshi_confidence_pct,
    )

    summary = build_summary(results, starting_bankroll)
    summary["meta"] = {
        "season": args.season,
        "starting_bankroll": round(starting_bankroll, 2),
        "kelly_fraction": round(float(bankroll_cfg.get("kelly_fraction", 0.25)), 4),
        "max_bet_pct": round(float(bankroll_cfg.get("max_bet_pct", 0.0)), 4),
        "min_bet": round(float(bankroll_cfg.get("min_bet", 1.0)), 4),
        "min_kalshi_edge_pct": round(float(min_kalshi_edge_pct), 4),
        "min_kalshi_confidence_pct": round(float(min_kalshi_confidence_pct), 4),
        "price_source": "closing (last trade before first pitch)",
    }

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    results.to_csv(RESULTS_PATH, sep="\t", index=False)
    with SUMMARY_PATH.open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print("\n=== Results ===")
    print(f"Total games:          {summary['total_games']}")
    print(f"With closing lines:   {summary['games_with_closing_lines']}")
    print(f"Bets placed:          {summary['bets_placed']} "
          f"({summary['wins']}W / {summary['losses']}L)")
    print(f"Win rate:             {summary['win_rate']:.1f}%")
    print(f"Over bets:            {summary['over_bets']} "
          f"(win rate {summary['over_win_rate']:.1f}%)")
    print(f"Under bets:           {summary['under_bets']} "
          f"(win rate {summary['under_win_rate']:.1f}%)")
    print(f"Avg edge:             {summary['avg_edge_pct']:+.2f}%")
    print(f"Total wagered:        ${summary['total_wagered']:,.2f}")
    print(f"Total P&L:            ${summary['total_pnl']:+,.2f}")
    print(f"ROI:                  {summary['roi_pct']:+.2f}%")
    print("\nSaved:")
    print(f"  {RESULTS_PATH.relative_to(PROJECT_DIR)}")
    print(f"  {SUMMARY_PATH.relative_to(PROJECT_DIR)}")


if __name__ == "__main__":
    main()
